# cli.travis

matrix:
  include: 
    - os: linux
      dist: trusty
      compiler: g++
    - os: linux
      compiler: clang++
    - os: osx
      compiler: clang++  

language: cpp

script:
- make
- ./xdhwebq --version

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
